[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "gway"
version = "0.4.59"
description = "Software Project Infrastructure by https://www.gelectriic.com"
requires-python = ">=3.10"
license = { file = "LICENSE.md" }
classifiers = [ "Programming Language :: Python :: 3", "Operating System :: OS Independent",]
dependencies = ['tomli>=2; python_version < "3.11"']
[[project.authors]]
name = "Rafael J. Guillén-Osorio"
email = "tecnologia@gelectriic.com"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.optional-dependencies]
dev = ["pytest"]
toml = ['tomli>=2; python_version < "3.11"']

[project.scripts]
gway = "gway:cli_main"

[project.urls]
Repository = "https://github.com/arthexis/gway.git"
Homepage = "https://arthexis.com"
Sponsor = "https://www.gelectriic.com/"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["gway*"]
