server {
    listen 80;
    listen [[::]]:80;
    server_name [domain];
    server_tokens off;

    if ($http_host = "") {
        return 444;
    }
    if ($host != [domain]) {
        return 444;
    }

    location ^~ /.well-known/acme-challenge/ {
        root [acme_webroot|/var/www/gway-acme];
        default_type text/plain;
    }

    location / {
        return 301 https://[domain]$request_uri;
    }
}
