"""GWAY project manager and command dispatcher."""

import os
import sys
from pathlib import Path

# Older setuptools-generated launchers may still import gway.cli directly.
# Detect the actual gway command before importing package internals so every
# CLI verb inherits noninteractive Git behavior even when the launcher itself
# has not yet been regenerated by an upgrade.
if Path(sys.argv[0]).name.lower() in {"gway", "gway.exe"}:
    os.environ["GIT_TERMINAL_PROMPT"] = "0"

from .api import Gway, gw, gway  # noqa: E402
from .sigils import gway_context  # noqa: E402

__all__ = ["Gway", "gway", "gw", "gway_context", "__version__"]

__version__ = "1.0.1"
