[Interface]
Address = [wire_client_address]
PrivateKey = [wire_client_private_key]

[Peer]
PublicKey = [wire_server_public_key]
Endpoint = [wire_server_endpoint]
AllowedIPs = [wire_server_tunnel_ip]/32
PersistentKeepalive = 25
