name: test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests
        run: gway test --coverage
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: work/screenshots/*.png
      - name: Install gh
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Comment screenshots on PR
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if compgen -G "work/screenshots/*.png" > /dev/null; then
            for img in work/screenshots/*.png; do
              encoded=$(base64 -w0 "$img")
              gh pr comment ${{ github.event.pull_request.number }} \
                --body "Screenshot from test: $(basename $img)

![$(basename $img)](data:image/png;base64,$encoded)"
            done
          fi
  raspi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm
      - name: Run tests on Raspberry Pi 4B image
        run: |
          docker run --rm --platform linux/arm/v7 --cap-add NET_ADMIN \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            arm32v7/python:3.11-slim bash -exc "\
              apt-get update; \
              apt-get install -y git iproute2; \
              ip link add wlan0 type dummy; \
              ip link add wlan1 type dummy; \
              ip link add wlan2 type dummy; \
              ip link add wlan3 type dummy; \
              ip link add eth0 type dummy; \
              pip install -r requirements.txt; \
              pip install -e .; \
              gway test --coverage; \
            "

