name: Test Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Run bandit
        run: bandit -q -r gway projects -b bandit-baseline.json
      - name: Run tests
        run: gway test --coverage
      - name: Mark ready for release
        if: success()
        run: echo "Ready for release to PyPI"
