server {
    listen 80;
    listen [[::]]:80;
    server_name [domain];
    server_tokens off;

    if ($http_host = "") {
        return 444;
    }
    if ($host != [domain]) {
        return 444;
    }

    location ^~ /.well-known/acme-challenge/ {
        root [acme_webroot|/var/www/gway-acme];
        default_type text/plain;
    }

    location / {
        return 301 https://[domain]$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [[::]]:443 ssl;
    server_name [domain];
    server_tokens off;

    if ($http_host = "") {
        return 444;
    }
    if ($host != [domain]) {
        return 444;
    }

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/letsencrypt/live/[domain]/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/[domain]/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "same-origin" always;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://[host]:[port];
    }
}
